sudo: required
services:
  - docker

before_install:
  - docker build -t shumenov/docker-react-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true shumenov/docker-react-1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-1"
  env: "Docker-react-1-env"
  bucket_name: "elasticbeanstalk-eu-north-1-565812099137"
  bucket_path: "docker-react-1"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
