sudo: required
services:
  - docker

before_install:
  - docker build -t shumenov/docker-react-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true shumenov/docker-react-1 npm run test -- --coverage
